import House1 from "@/app/assets/listings/House1.png";
import House2 from "@/app/assets/listings/House2.jpg";
import House3 from "@/app/assets/listings/House3.jpg";
import House4 from "@/app/assets/listings/House4.jpeg";
import House5 from "@/app/assets/listings/House5.jpg";
import House6 from "@/app/assets/listings/House6.jpg";

export const houses = [
  {
    listingsImage: House1,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 1,
  },
  {
    listingsImage: House2,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 2,
  },
  {
    listingsImage: House3,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 3,
  },
  {
    listingsImage: House4,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 4,
  },
  {
    listingsImage: House5,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 6,
  },
  {
    listingsImage: House6,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 7,
  },
  {
    listingsImage: House6,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 7,
  },
  {
    listingsImage: House6,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 7,
  },
  {
    listingsImage: House6,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 7,
  },
  {
    listingsImage: House6,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 7,
  },
  {
    listingsImage: House6,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 7,
  },
  {
    listingsImage: House6,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 7,
  },
  {
    listingsImage: House6,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 7,
  },
  {
    listingsImage: House6,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 7,
  },
  {
    listingsImage: House6,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 7,
  },
  {
    listingsImage: House6,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 7,
  },
  {
    listingsImage: House6,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 7,
  },
  {
    listingsImage: House6,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 7,
  },
  {
    listingsImage: House6,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 7,
  },
  {
    listingsImage: House6,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 7,
  },
  {
    listingsImage: House6,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 7,
  },
  {
    listingsImage: House6,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 7,
  },
  {
    listingsImage: House6,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 7,
  },
  {
    listingsImage: House6,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 7,
  },
  {
    listingsImage: House6,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 7,
  },
  {
    listingsImage: House6,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 7,
  },
  {
    listingsImage: House6,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 7,
  },
  {
    listingsImage: House6,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 7,
  },
  {
    listingsImage: House6,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 7,
  },
  {
    listingsImage: House6,
    location: "new york",
    area: 76,
    energyClass: "A",
    price: 300.0,
    id: 7,
  },
];
