import House1 from "@/app/assets/listings/House1.jpg";
import House2 from "@/app/assets/listings/House2.jpg";
import House3 from "@/app/assets/listings/House3.jpg";
import House4 from "@/app/assets/listings/House4.jpg";
import House5 from "@/app/assets/listings/House5.jpg";
import House6 from "@/app/assets/listings/House6.jpg";
import { Exo_2 } from "next/font/google";
import { property } from "three/examples/jsm/nodes/Nodes.js";

export const houses = [
  {
    title: "Spasious house in New York",
    listingsImage: House1,
    location: "San Francisco",
    area: 76,
    bedrooms: 2,
    bathrooms: 2,
    listingType: "Sale",
    propertyType: "Residential",
    elevator: true,
    balcony: true,
    heating: "central",
    garage: 1,
    floors: 2,
    energyClass: "A",
    furnished: "Partially",
    description:
      "Welcome to the Mod on Trenton! A contemporary new construction home on the cusp of vibrant neighborhoods Edgewood and Kirkwood. It features 5 bedrooms and 3.5 bathrooms, 2- car garage, a private main-level deck, and a stunning rooftop balcony featuring a cozy fire pit. This home boasts exterior columns and a large end-to-end porch that add charm and character. As you walk inside, you’re greeted with hardwood oak floors throughout, 9-foot ceilings, granite kitchen countertops, a spacious island for food prep or casual dining, and an oversized pantry. Step into your dining room and family room near the kitchen, creating a seamless flow perfect for dining and entertaining. On the main floor, will find a guest room with an ensuite bathroom, half bathroom, and spacious backyard.",
    price: 300000,
    yearBuilt: 1990,
    id: 1,
  },
  {
    title: "Spasious house in New York",
    listingsImage: House2,
    location: "new york",
    area: 76,
    bedrooms: 2,
    bathrooms: 1,
    listingType: "Sale",
    propertyType: "Residential",
    floors: 2,
    elevator: true,
    balcony: true,
    heating: "central",
    garage: 1,
    furnished: "Partially",
    description:
      "Welcome to the Mod on Trenton! A contemporary new construction home on the cusp of vibrant neighborhoods Edgewood and Kirkwood. It features 5 bedrooms and 3.5 bathrooms, 2- car garage, a private main-level deck, and a stunning rooftop balcony featuring a cozy fire pit. This home boasts exterior columns and a large end-to-end porch that add charm and character. As you walk inside, you’re greeted with hardwood oak floors throughout, 9-foot ceilings, granite kitchen countertops, a spacious island for food prep or casual dining, and an oversized pantry. Step into your dining room and family room near the kitchen, creating a seamless flow perfect for dining and entertaining. On the main floor, will find a guest room with an ensuite bathroom, half bathroom, and spacious backyard. Retreat to your first-floor deck off the dining room, your front porch or journey to the second-level balcony to relax. The owner’s retreat features private access to the rooftop balcony, a large master bathroom with spacious his and her closets, double vanity sinks, a separate walk-in shower with double jets that complement the home’s luxurious essence. Visit your nearby East Lake Golf Club, Edgewood Retail District, East Atlanta Village, Trolley Trail, and various dining options in this lively community. This home is convenient to I-20, 75/85, 285, the Beltline, Downtown Atlanta, Emory Hospital, Emory University, and other great amenities Atlanta has to offer. 3D renderings are for illustrative purposes only. Available in August/September 2024.",
    energyClass: "A",
    price: 3000000,
    yearBuilt: 1967,
    id: 2,
  },
  {
    title: "Spasious house in New York",
    listingsImage: House3,
    location: "new york",
    area: 76,
    bedrooms: 3,
    bathrooms: 1,
    elevator: true,
    balcony: true,
    furnished: "Partially",
    listingType: "Sale",
    propertyType: "Residential",
    floors: 2,
    heating: "central",
    garage: 1,
    description:
      "Welcome to the Mod on Trenton! A contemporary new construction home on the cusp of vibrant neighborhoods Edgewood and Kirkwood. It features 5 bedrooms and 3.5 bathrooms, 2- car garage, a private main-level deck, and a stunning rooftop balcony featuring a cozy fire pit. This home boasts exterior columns and a large end-to-end porch that add charm and character. As you walk inside, you’re greeted with hardwood oak floors throughout, 9-foot ceilings, granite kitchen countertops, a spacious island for food prep or casual dining, and an oversized pantry. Step into your dining room and family room near the kitchen, creating a seamless flow perfect for dining and entertaining. On the main floor, will find a guest room with an ensuite bathroom, half bathroom, and spacious backyard. Retreat to your first-floor deck off the dining room, your front porch or journey to the second-level balcony to relax. The owner’s retreat features private access to the rooftop balcony, a large master bathroom with spacious his and her closets, double vanity sinks, a separate walk-in shower with double jets that complement the home’s luxurious essence. Visit your nearby East Lake Golf Club, Edgewood Retail District, East Atlanta Village, Trolley Trail, and various dining options in this lively community. This home is convenient to I-20, 75/85, 285, the Beltline, Downtown Atlanta, Emory Hospital, Emory University, and other great amenities Atlanta has to offer. 3D renderings are for illustrative purposes only. Available in August/September 2024.",
    energyClass: "A",
    price: 300000,
    yearBuilt: 1980,
    id: 3,
  },
  {
    title: "Spasious house in New York",
    listingsImage: House4,
    location: "new york",
    area: 76,
    bedrooms: 4,
    bathrooms: 1,
    heating: "central",
    garage: 1,
    listingType: "Sale",
    propertyType: "Residential",
    floors: 2,
    elevator: true,
    balcony: true,
    furnished: "Partially",
    description:
      "Welcome to the Mod on Trenton! A contemporary new construction home on the cusp of vibrant neighborhoods Edgewood and Kirkwood. It features 5 bedrooms and 3.5 bathrooms, 2- car garage, a private main-level deck, and a stunning rooftop balcony featuring a cozy fire pit. This home boasts exterior columns and a large end-to-end porch that add charm and character. As you walk inside, you’re greeted with hardwood oak floors throughout, 9-foot ceilings, granite kitchen countertops, a spacious island for food prep or casual dining, and an oversized pantry. Step into your dining room and family room near the kitchen, creating a seamless flow perfect for dining and entertaining. On the main floor, will find a guest room with an ensuite bathroom, half bathroom, and spacious backyard. Retreat to your first-floor deck off the dining room, your front porch or journey to the second-level balcony to relax. The owner’s retreat features private access to the rooftop balcony, a large master bathroom with spacious his and her closets, double vanity sinks, a separate walk-in shower with double jets that complement the home’s luxurious essence. Visit your nearby East Lake Golf Club, Edgewood Retail District, East Atlanta Village, Trolley Trail, and various dining options in this lively community. This home is convenient to I-20, 75/85, 285, the Beltline, Downtown Atlanta, Emory Hospital, Emory University, and other great amenities Atlanta has to offer. 3D renderings are for illustrative purposes only. Available in August/September 2024.",
    energyClass: "A",
    price: 300000,
    yearBuilt: 1995,
    id: 4,
  },
  {
    title: "Spasious house in New York",
    listingsImage: House5,
    location: "new york",
    area: 76,
    bedrooms: 2,
    bathrooms: 1,
    listingType: "Sale",
    propertyType: "Residential",
    floors: 2,
    elevator: true,
    balcony: true,
    heating: "central",
    garage: 1,
    furnished: "Partially",
    description:
      "Welcome to the Mod on Trenton! A contemporary new construction home on the cusp of vibrant neighborhoods Edgewood and Kirkwood. It features 5 bedrooms and 3.5 bathrooms, 2- car garage, a private main-level deck, and a stunning rooftop balcony featuring a cozy fire pit. This home boasts exterior columns and a large end-to-end porch that add charm and character. As you walk inside, you’re greeted with hardwood oak floors throughout, 9-foot ceilings, granite kitchen countertops, a spacious island for food prep or casual dining, and an oversized pantry. Step into your dining room and family room near the kitchen, creating a seamless flow perfect for dining and entertaining. On the main floor, will find a guest room with an ensuite bathroom, half bathroom, and spacious backyard. Retreat to your first-floor deck off the dining room, your front porch or journey to the second-level balcony to relax. The owner’s retreat features private access to the rooftop balcony, a large master bathroom with spacious his and her closets, double vanity sinks, a separate walk-in shower with double jets that complement the home’s luxurious essence. Visit your nearby East Lake Golf Club, Edgewood Retail District, East Atlanta Village, Trolley Trail, and various dining options in this lively community. This home is convenient to I-20, 75/85, 285, the Beltline, Downtown Atlanta, Emory Hospital, Emory University, and other great amenities Atlanta has to offer. 3D renderings are for illustrative purposes only. Available in August/September 2024.",
    energyClass: "A",
    price: 300000,
    yearBuilt: 2017,
    id: 5,
  },
  {
    title: "Spasious house in New York",
    listingsImage: House6,
    location: "new york",
    area: 76,
    bedrooms: 2,
    bathrooms: 1,
    listingType: "Sale",
    propertyType: "Residential",
    floors: 2,
    elevator: true,
    balcony: true,
    heating: "central",
    garage: 1,
    furnished: "Partially",
    description:
      "Welcome to the Mod on Trenton! A contemporary new construction home on the cusp of vibrant neighborhoods Edgewood and Kirkwood. It features 5 bedrooms and 3.5 bathrooms, 2- car garage, a private main-level deck, and a stunning rooftop balcony featuring a cozy fire pit. This home boasts exterior columns and a large end-to-end porch that add charm and character. As you walk inside, you’re greeted with hardwood oak floors throughout, 9-foot ceilings, granite kitchen countertops, a spacious island for food prep or casual dining, and an oversized pantry. Step into your dining room and family room near the kitchen, creating a seamless flow perfect for dining and entertaining. On the main floor, will find a guest room with an ensuite bathroom, half bathroom, and spacious backyard. Retreat to your first-floor deck off the dining room, your front porch or journey to the second-level balcony to relax. The owner’s retreat features private access to the rooftop balcony, a large master bathroom with spacious his and her closets, double vanity sinks, a separate walk-in shower with double jets that complement the home’s luxurious essence. Visit your nearby East Lake Golf Club, Edgewood Retail District, East Atlanta Village, Trolley Trail, and various dining options in this lively community. This home is convenient to I-20, 75/85, 285, the Beltline, Downtown Atlanta, Emory Hospital, Emory University, and other great amenities Atlanta has to offer. 3D renderings are for illustrative purposes only. Available in August/September 2024.",
    energyClass: "A",
    price: 300000,
    yearBuilt: 1995,
    id: 6,
  },
  {
    title: "Spasious house in New York",
    listingsImage: House6,
    location: "new york",
    area: 76,
    bedrooms: 2,
    bathrooms: 2,
    listingType: "Sale",
    propertyType: "Residential",
    floors: 2,
    elevator: true,
    balcony: true,
    heating: "central",
    garage: 1,
    furnished: "Partially",
    description:
      "Welcome to the Mod on Trenton! A contemporary new construction home on the cusp of vibrant neighborhoods Edgewood and Kirkwood. It features 5 bedrooms and 3.5 bathrooms, 2- car garage, a private main-level deck, and a stunning rooftop balcony featuring a cozy fire pit. This home boasts exterior columns and a large end-to-end porch that add charm and character. As you walk inside, you’re greeted with hardwood oak floors throughout, 9-foot ceilings, granite kitchen countertops, a spacious island for food prep or casual dining, and an oversized pantry. Step into your dining room and family room near the kitchen, creating a seamless flow perfect for dining and entertaining. On the main floor, will find a guest room with an ensuite bathroom, half bathroom, and spacious backyard. Retreat to your first-floor deck off the dining room, your front porch or journey to the second-level balcony to relax. The owner’s retreat features private access to the rooftop balcony, a large master bathroom with spacious his and her closets, double vanity sinks, a separate walk-in shower with double jets that complement the home’s luxurious essence. Visit your nearby East Lake Golf Club, Edgewood Retail District, East Atlanta Village, Trolley Trail, and various dining options in this lively community. This home is convenient to I-20, 75/85, 285, the Beltline, Downtown Atlanta, Emory Hospital, Emory University, and other great amenities Atlanta has to offer. 3D renderings are for illustrative purposes only. Available in August/September 2024.",
    energyClass: "A",
    price: 300000,
    yearBuilt: 1995,
    id: 7,
  },
  {
    title: "Spasious house in New York",
    listingsImage: House6,
    location: "new york",
    area: 76,
    bedrooms: 2,
    bathrooms: 2,
    listingType: "Sale",
    propertyType: "Residential",
    floors: 2,
    elevator: true,
    balcony: true,
    heating: "central",
    garage: 1,
    furnished: "Partially",
    description:
      "Welcome to the Mod on Trenton! A contemporary new construction home on the cusp of vibrant neighborhoods Edgewood and Kirkwood. It features 5 bedrooms and 3.5 bathrooms, 2- car garage, a private main-level deck, and a stunning rooftop balcony featuring a cozy fire pit. This home boasts exterior columns and a large end-to-end porch that add charm and character. As you walk inside, you’re greeted with hardwood oak floors throughout, 9-foot ceilings, granite kitchen countertops, a spacious island for food prep or casual dining, and an oversized pantry. Step into your dining room and family room near the kitchen, creating a seamless flow perfect for dining and entertaining. On the main floor, will find a guest room with an ensuite bathroom, half bathroom, and spacious backyard. Retreat to your first-floor deck off the dining room, your front porch or journey to the second-level balcony to relax. The owner’s retreat features private access to the rooftop balcony, a large master bathroom with spacious his and her closets, double vanity sinks, a separate walk-in shower with double jets that complement the home’s luxurious essence. Visit your nearby East Lake Golf Club, Edgewood Retail District, East Atlanta Village, Trolley Trail, and various dining options in this lively community. This home is convenient to I-20, 75/85, 285, the Beltline, Downtown Atlanta, Emory Hospital, Emory University, and other great amenities Atlanta has to offer. 3D renderings are for illustrative purposes only. Available in August/September 2024.",
    energyClass: "A",
    price: 300000,
    yearBuilt: 1995,
    id: 8,
  },
  {
    title: "Spasious house in New York",
    listingsImage: House6,
    location: "new york",
    area: 76,
    bedrooms: 5,
    bathrooms: 2,
    elevator: true,
    balcony: true,
    heating: "central",
    garage: 1,
    furnished: "Partially",
    listingType: "Sale",
    propertyType: "Residential",
    floors: 2,
    description:
      "Welcome to the Mod on Trenton! A contemporary new construction home on the cusp of vibrant neighborhoods Edgewood and Kirkwood. It features 5 bedrooms and 3.5 bathrooms, 2- car garage, a private main-level deck, and a stunning rooftop balcony featuring a cozy fire pit. This home boasts exterior columns and a large end-to-end porch that add charm and character. As you walk inside, you’re greeted with hardwood oak floors throughout, 9-foot ceilings, granite kitchen countertops, a spacious island for food prep or casual dining, and an oversized pantry. Step into your dining room and family room near the kitchen, creating a seamless flow perfect for dining and entertaining. On the main floor, will find a guest room with an ensuite bathroom, half bathroom, and spacious backyard. Retreat to your first-floor deck off the dining room, your front porch or journey to the second-level balcony to relax. The owner’s retreat features private access to the rooftop balcony, a large master bathroom with spacious his and her closets, double vanity sinks, a separate walk-in shower with double jets that complement the home’s luxurious essence. Visit your nearby East Lake Golf Club, Edgewood Retail District, East Atlanta Village, Trolley Trail, and various dining options in this lively community. This home is convenient to I-20, 75/85, 285, the Beltline, Downtown Atlanta, Emory Hospital, Emory University, and other great amenities Atlanta has to offer. 3D renderings are for illustrative purposes only. Available in August/September 2024.",
    energyClass: "A",
    price: 300000,
    yearBuilt: 1995,
    id: 9,
  },
  {
    title: "Spasious house in New York",
    listingsImage: House6,
    location: "new york",
    area: 76,
    bedrooms: 3,
    bathrooms: 1,
    listingType: "Sale",

    propertyType: "Residential",
    floors: 2,
    elevator: true,
    balcony: true,
    garage: 1,
    heating: "central",
    furnished: "Partially",
    description:
      "Welcome to the Mod on Trenton! A contemporary new construction home on the cusp of vibrant neighborhoods Edgewood and Kirkwood. It features 5 bedrooms and 3.5 bathrooms, 2- car garage, a private main-level deck, and a stunning rooftop balcony featuring a cozy fire pit. This home boasts exterior columns and a large end-to-end porch that add charm and character. As you walk inside, you’re greeted with hardwood oak floors throughout, 9-foot ceilings, granite kitchen countertops, a spacious island for food prep or casual dining, and an oversized pantry. Step into your dining room and family room near the kitchen, creating a seamless flow perfect for dining and entertaining. On the main floor, will find a guest room with an ensuite bathroom, half bathroom, and spacious backyard. Retreat to your first-floor deck off the dining room, your front porch or journey to the second-level balcony to relax. The owner’s retreat features private access to the rooftop balcony, a large master bathroom with spacious his and her closets, double vanity sinks, a separate walk-in shower with double jets that complement the home’s luxurious essence. Visit your nearby East Lake Golf Club, Edgewood Retail District, East Atlanta Village, Trolley Trail, and various dining options in this lively community. This home is convenient to I-20, 75/85, 285, the Beltline, Downtown Atlanta, Emory Hospital, Emory University, and other great amenities Atlanta has to offer. 3D renderings are for illustrative purposes only. Available in August/September 2024.",
    energyClass: "A",
    price: 300000,
    yearBuilt: 2015,
    id: 10,
  },
];
